### ISSUE TITLE
Double locking bug one the lock shutdown_mtx?

### ISSUE THREAD

**Issue by ryancaicse** [cea-hpc/robinhood#119]
Hi, developers, in the below codes, it seems there is a double locking error (Line **1799**, **1830**) on the lock **shutdown_mtx**?  Thank you for your checking.

https://github.com/cea-hpc/robinhood/blob/43741870b34ae76e091e665d49a8e7cbbe5df08b/src/robinhood/rbh_daemon.c#L1799-L1830

**Comment by martinetd** [comment]
ryancaicse wrote on Wed, Sep 15, 2021 at 02:29:53AM -0700:
> Hi, developers, in the below codes, it seems there is a double locking
> error (Line **1799**, **1830**) on the lock **shutdown_mtx**?  Thank
> you for your checking.

Did you actually produce this error, or is this some static analysis
thing?

I have nothing against static analysis but unless the compiler reorders
the terminate_sig check, taking the lock on line 1799 means the process
won't enter the if block on line 1803 and thus won't lock again on line
1830, so that looks like a false positive to me.

**Comment by ryancaicse** [comment]
@martinetd OK, it is from static code analysis. Thank you for your time.
