### ISSUE TITLE
Want last_mod in file class

### ISSUE THREAD

**Issue by FayeG** [cea-hpc/robinhood#39]
Hi RBH complains if I add last_mod to file class stanza definition.

We have a use case for last_mod being in a file class rather than a policy stanza as we want to the output of the file class to be inputted to a custom python script.

How do we disable to the warnings?

**Comment by tl-cea** [comment]
Fileclass matching is quite static, it is not re-evaluated on each entry all the time.
However, a time-based condition (like last modification > 1d ago) is likely to change every second depending on entry age, and would require this age to be re-evaluated continuously.
That's why it's a bad idea to match a time condition in a fileclass definition: the entry will be processed when an event occurs on it. At this time it may or may not match. And then even if the entry's age enters the defined timeframe you will expect it to match your fileclass (in robinhood reports etc...), which won't be the case as not event happened on the entry, so the entry fileclass won"t be refreshed.
