### ISSUE TITLE
Database Table Design of the ENTRIES Table

### ISSUE THREAD

**Issue by gabrieleiannetti** [cea-hpc/robinhood#59]
Hello there,

I was wondering about the table design of the ENTRIES table.

Is there any specific reason for not putting indices on the ENTRIES table to the fields uid and gid?

Best regards,
Gabriele

**Comment by tl-cea** [comment]
You mean indexes?
If so, yes, there is a very important reason.
ENTRIES table is optimized to sustain high ingest rates (INSERT, UPDATE...). Indexes dramatically drop the insert/update performance, especially if the table contains millions of entries. That's why this table has no index.

However, the uid and gid fields are indexed in the ACCT_STAT table, that contains aggregated information about the filesystem. So if you need to make a fast request, maybe you will find the information you need in this table.
Thomas

**Comment by gabrieleiannetti** [comment]
Hello Thomas,

thanks for your answer.
Then your design decision is clear to me now.

Yes, I meant indexes.

If we would like to provide more precise information in shorter time about a specific user/group related to files,
putting indexes on the ENTRIES table would greatly improve the read performance in cost of disk usage and write performance.

Querying the ENTRIES table for files for a specific user/group results in a full table scan which is quite slow.

So if we would like to benefit from shorter read times on the ENTRIES table for retrieving more detailed information about files,
using indexes would be the appropriate way to go or not (from the actual state of the art)?

Gabriele

**Comment by tl-cea** [comment]
Hello,

If the information in ACCT_STAT table is not enough, and you need information in ENTRIES, then yes you can add an index uid and gid.
However, you must expect a drop of the ingest rate (scanning, and changelog ingestion will be slower)... It depends on the ingest rate performance you expect...
